# Add CLI packages as `brew "package"` and macOS apps as `cask "App"`.
# `./bootstrap.sh` applies this file after Homebrew is available.

brew "defaultbrowser"
brew "herdr"
brew "htop"
brew "eza"
brew "fzf"
brew "fzf-tab"
brew "neovim"
brew "mise"
brew "powerlevel10k"
brew "syncthing"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "spotify"
cask "whatsapp"
cask "microsoft-teams"
cask "ghostty"
cask "claude"
cask "chatgpt"
cask "claude-code"
cask "codex"
cask "codexbar"
cask "bitwarden"
cask "alt-tab"
cask "TheBoredTeam/boring-notch/boring-notch"
cask "brave-browser"
cask "obsidian"
cask "typewhisper"
cask "orbstack"
cask "hyperkey"
cask "raycast"
cask "eurkey-next"
cask "rider"
cask "dotnet-sdk"
cask "visual-studio-code"
cask "iina"
cask "jordanbaird-ice"
cask "nordvpn"
cask "steam"
cask "font-meslo-for-powerlevel10k"
cask "font-jetbrains-mono-nerd-font"
# Ghostty uses FiraCode Nerd Font Mono with the native Bold style.
cask "font-fira-code-nerd-font"
